[package]
name = "subql-contracts"
version = "0.1.0"
edition = "2021"
include = ["/rust", "/publish"]

[lib]
path = "rust/lib.rs"

[dependencies]
ethers = { git = "https://github.com/gakonst/ethers-rs.git", tag = "ethers-v2.0.7" }
paste = "1.0"
serde_json = "1.0"
